version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "06:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 25
  reviewers:
  - mprins
  assignees:
  - mprins
  ignore:
  - dependency-name: org.apache.lucene:lucene-analyzers-common
    versions:
    - "> 4.6.0"
  - dependency-name: org.apache.lucene:lucene-core
    versions:
    - "> 4.6.0"
