//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.04 at 05:13:28 PM CET 
//


package nl.b3p.csw.jaxb.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for outputSchemaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="outputSchemaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="csw:Record"/>
 *     &lt;enumeration value="csw:IsoRecord"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "outputSchemaType")
@XmlEnum
public enum OutputSchemaType {

    @XmlEnumValue("csw:Record")
    CSW_RECORD("csw:Record"),
    @XmlEnumValue("csw:IsoRecord")
    CSW_ISO_RECORD("csw:IsoRecord");
    private final String value;

    OutputSchemaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OutputSchemaType fromValue(String v) {
        for (OutputSchemaType c: OutputSchemaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
