//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:19:23 PM CEST 
//


package nl.b3p.csw.jaxb.gml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Value of an angle quantity provided in either degree-minute-second format or single value format.
 * 
 * <p>Java class for AngleChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AngleChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opengis.net/gml}angle"/>
 *         &lt;element ref="{http://www.opengis.net/gml}dmsAngle"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AngleChoiceType", propOrder = {
    "angle",
    "dmsAngle"
})
public class AngleChoiceType {

    @XmlElementRef(name = "angle", namespace = "http://www.opengis.net/gml", type = Angle.class)
    protected Angle angle;
    @XmlElementRef(name = "dmsAngle", namespace = "http://www.opengis.net/gml", type = DmsAngle.class)
    protected DmsAngle dmsAngle;

    /**
     * Default no-arg constructor
     * 
     */
    public AngleChoiceType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AngleChoiceType(final Angle angle, final DmsAngle dmsAngle) {
        this.angle = angle;
        this.dmsAngle = dmsAngle;
    }

    /**
     * Gets the value of the angle property.
     * 
     * @return
     *     possible object is
     *     {@link Angle }
     *     
     */
    public Angle getAngle() {
        return angle;
    }

    /**
     * Sets the value of the angle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Angle }
     *     
     */
    public void setAngle(Angle value) {
        this.angle = value;
    }

    /**
     * Gets the value of the dmsAngle property.
     * 
     * @return
     *     possible object is
     *     {@link DmsAngle }
     *     
     */
    public DmsAngle getDmsAngle() {
        return dmsAngle;
    }

    /**
     * Sets the value of the dmsAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmsAngle }
     *     
     */
    public void setDmsAngle(DmsAngle value) {
        this.dmsAngle = value;
    }

}
