//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.11 at 06:55:45 PM CET 
//


package nl.b3p.csw.jaxb.gml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A pattern or base for derived types used to specify complex types corresponding to an  unspecified UML association - either composition or aggregation.  Restricts the cardinality of Objects contained in the association to a maximum of one.  An instance of this type can contain an element representing an Object, or serve as a pointer to a remote Object.  
 * 
 * Descendents of this type can be restricted in an application schema to 
 * * allow only specified classes as valid participants in the aggregation
 * * allow only association by reference (i.e. empty the content model) or by value (i.e. remove the xlinks).    
 * 
 * When used for association by reference, the value of the gml:remoteSchema attribute can be used to locate a schema fragment that constrains the target instance.   
 * 
 * In many cases it is desirable to impose the constraint prohibiting the occurence of both reference and value in the same instance, as that would be ambiguous.  This is accomplished by adding a directive in the annotation element of the element declaration.  This directive can be in the form of normative prose, or can use a Schematron pattern to automatically constrain co-occurrence - see the declaration for _strictAssociation below.   
 * 
 * If co-occurence is not prohibited, then both a link and content may be present.  If this occurs in an instance, then the rule for interpretation is that the instance found by traversing the href provides the normative value of the property, and should be used when possible.  The value(s) included as content may be used if the remote instance cannot be resolved.  This may be considered to be a "cached" version of the value(s).
 * 
 * <p>Java class for AssociationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://www.opengis.net/gml}_Object"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opengis.net/gml}AssociationAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociationType", propOrder = {
    "object"
})
public class AssociationType {

    @XmlElementRef(name = "_Object", namespace = "http://www.opengis.net/gml", type = Object.class)
    protected JAXBElement<?> object;
    @XmlAttribute(namespace = "http://www.opengis.net/gml")
    @XmlSchemaType(name = "anyURI")
    protected String remoteSchema;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String type;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String href;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String role;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    @XmlSchemaType(name = "anyURI")
    protected String arcrole;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String title;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String show;
    @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
    protected String actuate;

    /**
     * Default no-arg constructor
     * 
     */
    public AssociationType() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AssociationType(final JAXBElement<?> object, final String remoteSchema, final String type, final String href, final String role, final String arcrole, final String title, final String show, final String actuate) {
        this.object = object;
        this.remoteSchema = remoteSchema;
        this.type = type;
        this.href = href;
        this.role = role;
        this.arcrole = arcrole;
        this.title = title;
        this.show = show;
        this.actuate = actuate;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link Solid }
     *     {@link MultiPolygon }
     *     {@link ConventionalUnit }
     *     {@link DerivedUnit }
     *     {@link MultiSolid }
     *     {@link MultiGeometry }
     *     {@link OrientableSurface }
     *     {@link UnitDefinition }
     *     {@link MultiCurve }
     *     {@link Ring }
     *     {@link GeometricAggregate }
     *     {@link DefinitionCollection }
     *     {@link MultiPoint }
     *     {@link AbstractCurve }
     *     {@link LinearRing }
     *     {@link MetaData }
     *     {@link PolyhedralSurface }
     *     {@link AbstractRing }
     *     {@link MultiSurface }
     *     {@link Definition }
     *     {@link DefinitionProxy }
     *     {@link Surface }
     *     {@link TriangulatedSurface }
     *     {@link LineString }
     *     {@link Tin }
     *     {@link Polygon }
     *     {@link GML }
     *     {@link GeometricPrimitive }
     *     {@link AbstractGeometry }
     *     {@link GenericMetaData }
     *     {@link MultiLineString }
     *     {@link Curve }
     *     {@link Object }
     *     {@link OrientableCurve }
     *     {@link AbstractSurface }
     *     {@link AbstractSolid }
     *     {@link BaseUnit }
     *     {@link Point }
     *     {@link Dictionary }
     *     {@link Bag }
     *     {@link Array }
     *     
     */
    public JAXBElement<?> getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link Solid }
     *     {@link MultiPolygon }
     *     {@link ConventionalUnit }
     *     {@link DerivedUnit }
     *     {@link MultiSolid }
     *     {@link MultiGeometry }
     *     {@link OrientableSurface }
     *     {@link UnitDefinition }
     *     {@link MultiCurve }
     *     {@link Ring }
     *     {@link GeometricAggregate }
     *     {@link DefinitionCollection }
     *     {@link MultiPoint }
     *     {@link AbstractCurve }
     *     {@link LinearRing }
     *     {@link MetaData }
     *     {@link PolyhedralSurface }
     *     {@link AbstractRing }
     *     {@link MultiSurface }
     *     {@link Definition }
     *     {@link DefinitionProxy }
     *     {@link Surface }
     *     {@link TriangulatedSurface }
     *     {@link LineString }
     *     {@link Tin }
     *     {@link Polygon }
     *     {@link GML }
     *     {@link GeometricPrimitive }
     *     {@link AbstractGeometry }
     *     {@link GenericMetaData }
     *     {@link MultiLineString }
     *     {@link Curve }
     *     {@link Object }
     *     {@link OrientableCurve }
     *     {@link AbstractSurface }
     *     {@link AbstractSolid }
     *     {@link BaseUnit }
     *     {@link Point }
     *     {@link Dictionary }
     *     {@link Bag }
     *     {@link Array }
     *     
     */
    public void setObject(JAXBElement<?> value) {
        this.object = ((JAXBElement<?> ) value);
    }

    /**
     * Gets the value of the remoteSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSchema() {
        return remoteSchema;
    }

    /**
     * Sets the value of the remoteSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSchema(String value) {
        this.remoteSchema = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "simple";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShow(String value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActuate(String value) {
        this.actuate = value;
    }

}
