//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:19:23 PM CEST 
//


package nl.b3p.csw.jaxb.elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import nl.b3p.csw.jaxb.terms.Abstract;
import nl.b3p.csw.jaxb.terms.AccessRights;
import nl.b3p.csw.jaxb.terms.Alternative;
import nl.b3p.csw.jaxb.terms.Audience;
import nl.b3p.csw.jaxb.terms.Available;
import nl.b3p.csw.jaxb.terms.BibliographicCitation;
import nl.b3p.csw.jaxb.terms.ConformsTo;
import nl.b3p.csw.jaxb.terms.Created;
import nl.b3p.csw.jaxb.terms.DateAccepted;
import nl.b3p.csw.jaxb.terms.DateCopyrighted;
import nl.b3p.csw.jaxb.terms.DateSubmitted;
import nl.b3p.csw.jaxb.terms.EducationLevel;
import nl.b3p.csw.jaxb.terms.Extent;
import nl.b3p.csw.jaxb.terms.HasFormat;
import nl.b3p.csw.jaxb.terms.HasPart;
import nl.b3p.csw.jaxb.terms.HasVersion;
import nl.b3p.csw.jaxb.terms.IsFormatOf;
import nl.b3p.csw.jaxb.terms.IsPartOf;
import nl.b3p.csw.jaxb.terms.IsReferencedBy;
import nl.b3p.csw.jaxb.terms.IsReplacedBy;
import nl.b3p.csw.jaxb.terms.IsRequiredBy;
import nl.b3p.csw.jaxb.terms.IsVersionOf;
import nl.b3p.csw.jaxb.terms.Issued;
import nl.b3p.csw.jaxb.terms.License;
import nl.b3p.csw.jaxb.terms.Mediator;
import nl.b3p.csw.jaxb.terms.Medium;
import nl.b3p.csw.jaxb.terms.Modified;
import nl.b3p.csw.jaxb.terms.Provenance;
import nl.b3p.csw.jaxb.terms.References;
import nl.b3p.csw.jaxb.terms.Replaces;
import nl.b3p.csw.jaxb.terms.Requires;
import nl.b3p.csw.jaxb.terms.RightsHolder;
import nl.b3p.csw.jaxb.terms.Spatial;
import nl.b3p.csw.jaxb.terms.TableOfContents;
import nl.b3p.csw.jaxb.terms.Temporal;
import nl.b3p.csw.jaxb.terms.Valid;


/**
 * This type definition is included as a convenience for schema authors 
 *       who need a container element for all of the DC elements.
 * 
 * <p>Java class for elementContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://purl.org/dc/elements/1.1/}DC-element-set"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementContainer", propOrder = {
    "dcElement"
})
public class ElementContainer {

    @XmlElementRef(name = "DC-element", namespace = "http://purl.org/dc/elements/1.1/", type = DCElement.class)
    protected List<JAXBElement<SimpleLiteral>> dcElement;

    /**
     * Default no-arg constructor
     * 
     */
    public ElementContainer() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public ElementContainer(final List<JAXBElement<SimpleLiteral>> dcElement) {
        this.dcElement = dcElement;
    }

    /**
     * Gets the value of the dcElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDCElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Coverage }
     * {@link Language }
     * {@link HasFormat }
     * {@link Replaces }
     * {@link ConformsTo }
     * {@link HasVersion }
     * {@link Subject }
     * {@link Issued }
     * {@link License }
     * {@link DateCopyrighted }
     * {@link Abstract }
     * {@link BibliographicCitation }
     * {@link Title }
     * {@link Alternative }
     * {@link Date }
     * {@link References }
     * {@link IsReferencedBy }
     * {@link HasPart }
     * {@link TableOfContents }
     * {@link Relation }
     * {@link DateSubmitted }
     * {@link Type }
     * {@link Contributor }
     * {@link Publisher }
     * {@link Rights }
     * {@link Temporal }
     * {@link IsRequiredBy }
     * {@link AccessRights }
     * {@link Mediator }
     * {@link EducationLevel }
     * {@link Created }
     * {@link Audience }
     * {@link DateAccepted }
     * {@link Format }
     * {@link IsPartOf }
     * {@link IsFormatOf }
     * {@link RightsHolder }
     * {@link IsVersionOf }
     * {@link Requires }
     * {@link Valid }
     * {@link Source }
     * {@link DCElement }
     * {@link Modified }
     * {@link IsReplacedBy }
     * {@link Medium }
     * {@link Creator }
     * {@link Available }
     * {@link Provenance }
     * {@link Identifier }
     * {@link Extent }
     * {@link Spatial }
     * {@link Description }
     * 
     * 
     */
    public List<JAXBElement<SimpleLiteral>> getDCElement() {
        if (dcElement == null) {
            dcElement = new ArrayList<JAXBElement<SimpleLiteral>>();
        }
        return this.dcElement;
    }

}
