//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:19:23 PM CEST 
//


package nl.b3p.csw.jaxb.terms;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import nl.b3p.csw.jaxb.elements.SimpleLiteral;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.b3p.csw.jaxb.terms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.b3p.csw.jaxb.terms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TableOfContents }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "tableOfContents", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "description")
    public TableOfContents createTableOfContents(SimpleLiteral value) {
        return new TableOfContents(value);
    }

    /**
     * Create an instance of {@link DateCopyrighted }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateCopyrighted", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public DateCopyrighted createDateCopyrighted(SimpleLiteral value) {
        return new DateCopyrighted(value);
    }

    /**
     * Create an instance of {@link Spatial }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "spatial", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "coverage")
    public Spatial createSpatial(SimpleLiteral value) {
        return new Spatial(value);
    }

    /**
     * Create an instance of {@link Mediator }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "mediator", substitutionHeadNamespace = "http://purl.org/dc/terms/", substitutionHeadName = "audience")
    public Mediator createMediator(SimpleLiteral value) {
        return new Mediator(value);
    }

    /**
     * Create an instance of {@link HasVersion }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasVersion", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public HasVersion createHasVersion(SimpleLiteral value) {
        return new HasVersion(value);
    }

    /**
     * Create an instance of {@link BibliographicCitation }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "bibliographicCitation", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "identifier")
    public BibliographicCitation createBibliographicCitation(SimpleLiteral value) {
        return new BibliographicCitation(value);
    }

    /**
     * Create an instance of {@link Extent }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "extent", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "format")
    public Extent createExtent(SimpleLiteral value) {
        return new Extent(value);
    }

    /**
     * Create an instance of {@link AccessRights }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "accessRights", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "rights")
    public AccessRights createAccessRights(SimpleLiteral value) {
        return new AccessRights(value);
    }

    /**
     * Create an instance of {@link Abstract }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "abstract", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "description")
    public Abstract createAbstract(SimpleLiteral value) {
        return new Abstract(value);
    }

    /**
     * Create an instance of {@link Audience }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "audience", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "DC-element")
    public Audience createAudience(SimpleLiteral value) {
        return new Audience(value);
    }

    /**
     * Create an instance of {@link HasFormat }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasFormat", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public HasFormat createHasFormat(SimpleLiteral value) {
        return new HasFormat(value);
    }

    /**
     * Create an instance of {@link RightsHolder }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "rightsHolder", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "DC-element")
    public RightsHolder createRightsHolder(SimpleLiteral value) {
        return new RightsHolder(value);
    }

    /**
     * Create an instance of {@link Requires }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "requires", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public Requires createRequires(SimpleLiteral value) {
        return new Requires(value);
    }

    /**
     * Create an instance of {@link Issued }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "issued", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public Issued createIssued(SimpleLiteral value) {
        return new Issued(value);
    }

    /**
     * Create an instance of {@link License }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "license", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "rights")
    public License createLicense(SimpleLiteral value) {
        return new License(value);
    }

    /**
     * Create an instance of {@link ConformsTo }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "conformsTo", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public ConformsTo createConformsTo(SimpleLiteral value) {
        return new ConformsTo(value);
    }

    /**
     * Create an instance of {@link Medium }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "medium", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "format")
    public Medium createMedium(SimpleLiteral value) {
        return new Medium(value);
    }

    /**
     * Create an instance of {@link DateSubmitted }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateSubmitted", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public DateSubmitted createDateSubmitted(SimpleLiteral value) {
        return new DateSubmitted(value);
    }

    /**
     * Create an instance of {@link References }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "references", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public References createReferences(SimpleLiteral value) {
        return new References(value);
    }

    /**
     * Create an instance of {@link Created }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "created", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public Created createCreated(SimpleLiteral value) {
        return new Created(value);
    }

    /**
     * Create an instance of {@link Provenance }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "provenance", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "DC-element")
    public Provenance createProvenance(SimpleLiteral value) {
        return new Provenance(value);
    }

    /**
     * Create an instance of {@link DateAccepted }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "dateAccepted", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public DateAccepted createDateAccepted(SimpleLiteral value) {
        return new DateAccepted(value);
    }

    /**
     * Create an instance of {@link Available }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "available", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public Available createAvailable(SimpleLiteral value) {
        return new Available(value);
    }

    /**
     * Create an instance of {@link IsRequiredBy }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isRequiredBy", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsRequiredBy createIsRequiredBy(SimpleLiteral value) {
        return new IsRequiredBy(value);
    }

    /**
     * Create an instance of {@link Valid }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "valid", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public Valid createValid(SimpleLiteral value) {
        return new Valid(value);
    }

    /**
     * Create an instance of {@link IsFormatOf }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isFormatOf", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsFormatOf createIsFormatOf(SimpleLiteral value) {
        return new IsFormatOf(value);
    }

    /**
     * Create an instance of {@link IsVersionOf }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isVersionOf", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsVersionOf createIsVersionOf(SimpleLiteral value) {
        return new IsVersionOf(value);
    }

    /**
     * Create an instance of {@link IsReferencedBy }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isReferencedBy", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsReferencedBy createIsReferencedBy(SimpleLiteral value) {
        return new IsReferencedBy(value);
    }

    /**
     * Create an instance of {@link Temporal }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "temporal", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "coverage")
    public Temporal createTemporal(SimpleLiteral value) {
        return new Temporal(value);
    }

    /**
     * Create an instance of {@link HasPart }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "hasPart", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public HasPart createHasPart(SimpleLiteral value) {
        return new HasPart(value);
    }

    /**
     * Create an instance of {@link EducationLevel }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "educationLevel", substitutionHeadNamespace = "http://purl.org/dc/terms/", substitutionHeadName = "audience")
    public EducationLevel createEducationLevel(SimpleLiteral value) {
        return new EducationLevel(value);
    }

    /**
     * Create an instance of {@link IsReplacedBy }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isReplacedBy", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsReplacedBy createIsReplacedBy(SimpleLiteral value) {
        return new IsReplacedBy(value);
    }

    /**
     * Create an instance of {@link IsPartOf }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "isPartOf", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public IsPartOf createIsPartOf(SimpleLiteral value) {
        return new IsPartOf(value);
    }

    /**
     * Create an instance of {@link Alternative }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "alternative", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "title")
    public Alternative createAlternative(SimpleLiteral value) {
        return new Alternative(value);
    }

    /**
     * Create an instance of {@link Modified }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "modified", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "date")
    public Modified createModified(SimpleLiteral value) {
        return new Modified(value);
    }

    /**
     * Create an instance of {@link Replaces }}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/terms/", name = "replaces", substitutionHeadNamespace = "http://purl.org/dc/elements/1.1/", substitutionHeadName = "relation")
    public Replaces createReplaces(SimpleLiteral value) {
        return new Replaces(value);
    }

}
