//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 09:11:40 PM CET 
//


package nl.b3p.csw.jaxb.ows;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.b3p.csw.jaxb.ows package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HTTPGet_QNAME = new QName("http://www.opengis.net/ows", "Get");
    private final static QName _HTTPPost_QNAME = new QName("http://www.opengis.net/ows", "Post");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.b3p.csw.jaxb.ows
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCapabilitiesType }
     * 
     */
    public GetCapabilitiesType createGetCapabilitiesType() {
        return new GetCapabilitiesType();
    }

    /**
     * Create an instance of {@link OnlineResourceType }
     * 
     */
    public OnlineResourceType createOnlineResourceType() {
        return new OnlineResourceType();
    }

    /**
     * Create an instance of {@link RequestMethodType }
     * 
     */
    public RequestMethodType createRequestMethodType() {
        return new RequestMethodType();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link KeywordsType }
     * 
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link WGS84BoundingBoxType }
     * 
     */
    public WGS84BoundingBoxType createWGS84BoundingBoxType() {
        return new WGS84BoundingBoxType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link AcceptVersionsType }
     * 
     */
    public AcceptVersionsType createAcceptVersionsType() {
        return new AcceptVersionsType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CapabilitiesBaseType }
     * 
     */
    public CapabilitiesBaseType createCapabilitiesBaseType() {
        return new CapabilitiesBaseType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link AcceptFormatsType }
     * 
     */
    public AcceptFormatsType createAcceptFormatsType() {
        return new AcceptFormatsType();
    }

    /**
     * Create an instance of {@link TelephoneType }
     * 
     */
    public TelephoneType createTelephoneType() {
        return new TelephoneType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link ExceptionReport }
     * 
     */
    public ExceptionReport createExceptionReport() {
        return new ExceptionReport();
    }

    /**
     * Create an instance of {@link BoundingBoxType }
     * 
     */
    public BoundingBoxType createBoundingBoxType() {
        return new BoundingBoxType();
    }

    /**
     * Create an instance of {@link ServiceProvider }
     * 
     */
    public ServiceProvider createServiceProvider() {
        return new ServiceProvider();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link DCP }
     * 
     */
    public DCP createDCP() {
        return new DCP();
    }

    /**
     * Create an instance of {@link ResponsiblePartySubsetType }
     * 
     */
    public ResponsiblePartySubsetType createResponsiblePartySubsetType() {
        return new ResponsiblePartySubsetType();
    }

    /**
     * Create an instance of {@link HTTP }
     * 
     */
    public HTTP createHTTP() {
        return new HTTP();
    }

    /**
     * Create an instance of {@link SectionsType }
     * 
     */
    public SectionsType createSectionsType() {
        return new SectionsType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link ServiceIdentification }
     * 
     */
    public ServiceIdentification createServiceIdentification() {
        return new ServiceIdentification();
    }

    /**
     * Create an instance of {@link OperationsMetadata }
     * 
     */
    public OperationsMetadata createOperationsMetadata() {
        return new OperationsMetadata();
    }

    /**
     * Create an instance of {@link ResponsiblePartyType }
     * 
     */
    public ResponsiblePartyType createResponsiblePartyType() {
        return new ResponsiblePartyType();
    }

    /**
     * Create an instance of {@link Keywords }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Keywords")
    public Keywords createKeywords(KeywordsType value) {
        return new Keywords(value);
    }

    /**
     * Create an instance of {@link Language }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public Language createLanguage(String value) {
        return new Language(value);
    }

    /**
     * Create an instance of {@link Role }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Role")
    public Role createRole(CodeType value) {
        return new Role(value);
    }

    /**
     * Create an instance of {@link IndividualName }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "IndividualName")
    public IndividualName createIndividualName(String value) {
        return new IndividualName(value);
    }

    /**
     * Create an instance of {@link Title }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Title")
    public Title createTitle(String value) {
        return new Title(value);
    }

    /**
     * Create an instance of {@link ContactInfo }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "ContactInfo")
    public ContactInfo createContactInfo(ContactType value) {
        return new ContactInfo(value);
    }

    /**
     * Create an instance of {@link SupportedCRS }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "SupportedCRS", substitutionHeadNamespace = "http://www.opengis.net/ows", substitutionHeadName = "AvailableCRS")
    public SupportedCRS createSupportedCRS(String value) {
        return new SupportedCRS(value);
    }

    /**
     * Create an instance of {@link OutputFormat }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "OutputFormat")
    public OutputFormat createOutputFormat(String value) {
        return new OutputFormat(value);
    }

    /**
     * Create an instance of {@link AvailableCRS }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "AvailableCRS")
    public AvailableCRS createAvailableCRS(String value) {
        return new AvailableCRS(value);
    }

    /**
     * Create an instance of {@link Fees }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Fees")
    public Fees createFees(String value) {
        return new Fees(value);
    }

    /**
     * Create an instance of {@link Exception }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Exception")
    public Exception createException(ExceptionType value) {
        return new Exception(value);
    }

    /**
     * Create an instance of {@link Metadata }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Metadata")
    public Metadata createMetadata(MetadataType value) {
        return new Metadata(value);
    }

    /**
     * Create an instance of {@link PointOfContact }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "PointOfContact")
    public PointOfContact createPointOfContact(ResponsiblePartyType value) {
        return new PointOfContact(value);
    }

    /**
     * Create an instance of {@link Identifier }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Identifier")
    public Identifier createIdentifier(CodeType value) {
        return new Identifier(value);
    }

    /**
     * Create an instance of {@link OrganisationName }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "OrganisationName")
    public OrganisationName createOrganisationName(String value) {
        return new OrganisationName(value);
    }

    /**
     * Create an instance of {@link AbstractMetaData }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "AbstractMetaData")
    public AbstractMetaData createAbstractMetaData(Object value) {
        return new AbstractMetaData(value);
    }

    /**
     * Create an instance of {@link Abstract }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Abstract")
    public Abstract createAbstract(String value) {
        return new Abstract(value);
    }

    /**
     * Create an instance of {@link ExtendedCapabilities }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "ExtendedCapabilities")
    public ExtendedCapabilities createExtendedCapabilities(Object value) {
        return new ExtendedCapabilities(value);
    }

    /**
     * Create an instance of {@link BoundingBox }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "BoundingBox")
    public BoundingBox createBoundingBox(BoundingBoxType value) {
        return new BoundingBox(value);
    }

    /**
     * Create an instance of {@link AccessConstraints }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "AccessConstraints")
    public AccessConstraints createAccessConstraints(String value) {
        return new AccessConstraints(value);
    }

    /**
     * Create an instance of {@link PositionName }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "PositionName")
    public PositionName createPositionName(String value) {
        return new PositionName(value);
    }

    /**
     * Create an instance of {@link WGS84BoundingBox }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "WGS84BoundingBox", substitutionHeadNamespace = "http://www.opengis.net/ows", substitutionHeadName = "BoundingBox")
    public WGS84BoundingBox createWGS84BoundingBox(WGS84BoundingBoxType value) {
        return new WGS84BoundingBox(value);
    }

    /**
     * Create an instance of {@link GetCapabilities }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "GetCapabilities")
    public GetCapabilities createGetCapabilities(GetCapabilitiesType value) {
        return new GetCapabilities(value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Get", scope = HTTP.class)
    public JAXBElement<RequestMethodType> createHTTPGet(RequestMethodType value) {
        return new JAXBElement<RequestMethodType>(_HTTPGet_QNAME, RequestMethodType.class, HTTP.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/ows", name = "Post", scope = HTTP.class)
    public JAXBElement<RequestMethodType> createHTTPPost(RequestMethodType value) {
        return new JAXBElement<RequestMethodType>(_HTTPPost_QNAME, RequestMethodType.class, HTTP.class, value);
    }

}
