//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.10 at 04:19:23 PM CEST 
//


package nl.b3p.csw.jaxb.csw;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.b3p.csw.jaxb.csw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.b3p.csw.jaxb.csw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcknowledgementType }
     * 
     */
    public AcknowledgementType createAcknowledgementType() {
        return new AcknowledgementType();
    }

    /**
     * Create an instance of {@link SchemaComponentType }
     * 
     */
    public SchemaComponentType createSchemaComponentType() {
        return new SchemaComponentType();
    }

    /**
     * Create an instance of {@link GetDomainType }
     * 
     */
    public GetDomainType createGetDomainType() {
        return new GetDomainType();
    }

    /**
     * Create an instance of {@link RequestStatusType }
     * 
     */
    public RequestStatusType createRequestStatusType() {
        return new RequestStatusType();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link SummaryRecordType }
     * 
     */
    public SummaryRecordType createSummaryRecordType() {
        return new SummaryRecordType();
    }

    /**
     * Create an instance of {@link DescribeRecordType }
     * 
     */
    public DescribeRecordType createDescribeRecordType() {
        return new DescribeRecordType();
    }

    /**
     * Create an instance of {@link DistributedSearchType }
     * 
     */
    public DistributedSearchType createDistributedSearchType() {
        return new DistributedSearchType();
    }

    /**
     * Create an instance of {@link InsertType }
     * 
     */
    public InsertType createInsertType() {
        return new InsertType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link GetCapabilitiesType }
     * 
     */
    public GetCapabilitiesType createGetCapabilitiesType() {
        return new GetCapabilitiesType();
    }

    /**
     * Create an instance of {@link ElementSetNameType }
     * 
     */
    public ElementSetNameType createElementSetNameType() {
        return new ElementSetNameType();
    }

    /**
     * Create an instance of {@link QueryConstraintType }
     * 
     */
    public QueryConstraintType createQueryConstraintType() {
        return new QueryConstraintType();
    }

    /**
     * Create an instance of {@link HarvestResponseType }
     * 
     */
    public HarvestResponseType createHarvestResponseType() {
        return new HarvestResponseType();
    }

    /**
     * Create an instance of {@link TransactionResponseType }
     * 
     */
    public TransactionResponseType createTransactionResponseType() {
        return new TransactionResponseType();
    }

    /**
     * Create an instance of {@link DomainValuesType }
     * 
     */
    public DomainValuesType createDomainValuesType() {
        return new DomainValuesType();
    }

    /**
     * Create an instance of {@link ListOfValuesType }
     * 
     */
    public ListOfValuesType createListOfValuesType() {
        return new ListOfValuesType();
    }

    /**
     * Create an instance of {@link InsertResultType }
     * 
     */
    public InsertResultType createInsertResultType() {
        return new InsertResultType();
    }

    /**
     * Create an instance of {@link DeleteType }
     * 
     */
    public DeleteType createDeleteType() {
        return new DeleteType();
    }

    /**
     * Create an instance of {@link TransactionSummaryType }
     * 
     */
    public TransactionSummaryType createTransactionSummaryType() {
        return new TransactionSummaryType();
    }

    /**
     * Create an instance of {@link SearchResultsType }
     * 
     */
    public SearchResultsType createSearchResultsType() {
        return new SearchResultsType();
    }

    /**
     * Create an instance of {@link GetRecordByIdResponseType }
     * 
     */
    public GetRecordByIdResponseType createGetRecordByIdResponseType() {
        return new GetRecordByIdResponseType();
    }

    /**
     * Create an instance of {@link CapabilitiesType }
     * 
     */
    public CapabilitiesType createCapabilitiesType() {
        return new CapabilitiesType();
    }

    /**
     * Create an instance of {@link BriefRecordType }
     * 
     */
    public BriefRecordType createBriefRecordType() {
        return new BriefRecordType();
    }

    /**
     * Create an instance of {@link DescribeRecordResponseType }
     * 
     */
    public DescribeRecordResponseType createDescribeRecordResponseType() {
        return new DescribeRecordResponseType();
    }

    /**
     * Create an instance of {@link UpdateType }
     * 
     */
    public UpdateType createUpdateType() {
        return new UpdateType();
    }

    /**
     * Create an instance of {@link HarvestType }
     * 
     */
    public HarvestType createHarvestType() {
        return new HarvestType();
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link RangeOfValuesType }
     * 
     */
    public RangeOfValuesType createRangeOfValuesType() {
        return new RangeOfValuesType();
    }

    /**
     * Create an instance of {@link RecordPropertyType }
     * 
     */
    public RecordPropertyType createRecordPropertyType() {
        return new RecordPropertyType();
    }

    /**
     * Create an instance of {@link ConceptualSchemeType }
     * 
     */
    public ConceptualSchemeType createConceptualSchemeType() {
        return new ConceptualSchemeType();
    }

    /**
     * Create an instance of {@link DCMIRecordType }
     * 
     */
    public DCMIRecordType createDCMIRecordType() {
        return new DCMIRecordType();
    }

    /**
     * Create an instance of {@link GetRecordByIdType }
     * 
     */
    public GetRecordByIdType createGetRecordByIdType() {
        return new GetRecordByIdType();
    }

    /**
     * Create an instance of {@link EchoedRequestType }
     * 
     */
    public EchoedRequestType createEchoedRequestType() {
        return new EchoedRequestType();
    }

    /**
     * Create an instance of {@link GetDomainResponseType }
     * 
     */
    public GetDomainResponseType createGetDomainResponseType() {
        return new GetDomainResponseType();
    }

    /**
     * Create an instance of {@link QueryType }
     * 
     */
    public QueryType createQueryType() {
        return new QueryType();
    }

    /**
     * Create an instance of {@link GetRecordsType }
     * 
     */
    public GetRecordsType createGetRecordsType() {
        return new GetRecordsType();
    }

    /**
     * Create an instance of {@link GetRecordsResponseType }
     * 
     */
    public GetRecordsResponseType createGetRecordsResponseType() {
        return new GetRecordsResponseType();
    }

    /**
     * Create an instance of {@link AbstractQuery }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "AbstractQuery")
    public AbstractQuery createAbstractQuery(AbstractQueryType value) {
        return new AbstractQuery(value);
    }

    /**
     * Create an instance of {@link Acknowledgement }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Acknowledgement")
    public Acknowledgement createAcknowledgement(AcknowledgementType value) {
        return new Acknowledgement(value);
    }

    /**
     * Create an instance of {@link Constraint }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Constraint")
    public Constraint createConstraint(QueryConstraintType value) {
        return new Constraint(value);
    }

    /**
     * Create an instance of {@link ElementSetName }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "ElementSetName", defaultValue = "summary")
    public ElementSetName createElementSetName(ElementSetNameType value) {
        return new ElementSetName(value);
    }

    /**
     * Create an instance of {@link Harvest }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Harvest")
    public Harvest createHarvest(HarvestType value) {
        return new Harvest(value);
    }

    /**
     * Create an instance of {@link Transaction }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Transaction")
    public Transaction createTransaction(TransactionType value) {
        return new Transaction(value);
    }

    /**
     * Create an instance of {@link SummaryRecord }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "SummaryRecord", substitutionHeadNamespace = "http://www.opengis.net/cat/csw/2.0.2", substitutionHeadName = "AbstractRecord")
    public SummaryRecord createSummaryRecord(SummaryRecordType value) {
        return new SummaryRecord(value);
    }

    /**
     * Create an instance of {@link Query }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Query", substitutionHeadNamespace = "http://www.opengis.net/cat/csw/2.0.2", substitutionHeadName = "AbstractQuery")
    public Query createQuery(QueryType value) {
        return new Query(value);
    }

    /**
     * Create an instance of {@link HarvestResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "HarvestResponse")
    public HarvestResponse createHarvestResponse(HarvestResponseType value) {
        return new HarvestResponse(value);
    }

    /**
     * Create an instance of {@link AbstractRecord }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "AbstractRecord")
    public AbstractRecord createAbstractRecord(AbstractRecordType value) {
        return new AbstractRecord(value);
    }

    /**
     * Create an instance of {@link GetDomainResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetDomainResponse")
    public GetDomainResponse createGetDomainResponse(GetDomainResponseType value) {
        return new GetDomainResponse(value);
    }

    /**
     * Create an instance of {@link RecordProperty }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "RecordProperty")
    public RecordProperty createRecordProperty(RecordPropertyType value) {
        return new RecordProperty(value);
    }

    /**
     * Create an instance of {@link GetRecordByIdResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetRecordByIdResponse")
    public GetRecordByIdResponse createGetRecordByIdResponse(GetRecordByIdResponseType value) {
        return new GetRecordByIdResponse(value);
    }

    /**
     * Create an instance of {@link DescribeRecordResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "DescribeRecordResponse")
    public DescribeRecordResponse createDescribeRecordResponse(DescribeRecordResponseType value) {
        return new DescribeRecordResponse(value);
    }

    /**
     * Create an instance of {@link GetRecords }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetRecords")
    public GetRecords createGetRecords(GetRecordsType value) {
        return new GetRecords(value);
    }

    /**
     * Create an instance of {@link GetRecordsResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetRecordsResponse")
    public GetRecordsResponse createGetRecordsResponse(GetRecordsResponseType value) {
        return new GetRecordsResponse(value);
    }

    /**
     * Create an instance of {@link DCMIRecord }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "DCMIRecord", substitutionHeadNamespace = "http://www.opengis.net/cat/csw/2.0.2", substitutionHeadName = "AbstractRecord")
    public DCMIRecord createDCMIRecord(DCMIRecordType value) {
        return new DCMIRecord(value);
    }

    /**
     * Create an instance of {@link DescribeRecord }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "DescribeRecord")
    public DescribeRecord createDescribeRecord(DescribeRecordType value) {
        return new DescribeRecord(value);
    }

    /**
     * Create an instance of {@link Record }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Record", substitutionHeadNamespace = "http://www.opengis.net/cat/csw/2.0.2", substitutionHeadName = "AbstractRecord")
    public Record createRecord(RecordType value) {
        return new Record(value);
    }

    /**
     * Create an instance of {@link BriefRecord }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "BriefRecord", substitutionHeadNamespace = "http://www.opengis.net/cat/csw/2.0.2", substitutionHeadName = "AbstractRecord")
    public BriefRecord createBriefRecord(BriefRecordType value) {
        return new BriefRecord(value);
    }

    /**
     * Create an instance of {@link GetCapabilities }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetCapabilities")
    public GetCapabilities createGetCapabilities(GetCapabilitiesType value) {
        return new GetCapabilities(value);
    }

    /**
     * Create an instance of {@link TransactionResponse }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "TransactionResponse")
    public TransactionResponse createTransactionResponse(TransactionResponseType value) {
        return new TransactionResponse(value);
    }

    /**
     * Create an instance of {@link Capabilities }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "Capabilities")
    public Capabilities createCapabilities(CapabilitiesType value) {
        return new Capabilities(value);
    }

    /**
     * Create an instance of {@link GetRecordById }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetRecordById")
    public GetRecordById createGetRecordById(GetRecordByIdType value) {
        return new GetRecordById(value);
    }

    /**
     * Create an instance of {@link GetDomain }}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/cat/csw/2.0.2", name = "GetDomain")
    public GetDomain createGetDomain(GetDomainType value) {
        return new GetDomain(value);
    }

}
